server:
  port: 8084
  servlet:
    context-path: /file
spring:
  application:
    name: file-service
  data:
    mongodb:
      uri: mongodb://root:251101@localhost:27017/file-service?authSource=admin

app:
  file:
    storage-dir: D:/Microservice/bookteria-demo/upload
    download-prefix: http://localhost:8888/api/v1/file/media/