server:
  port: 8081
  servlet:
    context-path: /profile

spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 25112001
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
file:
  services:
    url: http://localhost:8084
